env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        base-ref: ${{ github.event.pull_request.base.sha || '0.1.0' }}
        comment-summary-in-pr: on-failure
        head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
        license-check: false
        vulnerability-check: true
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Compile
      run: ./mvnw clean package -DskipTests
    - continue-on-error: true
      name: Test
      run: ./mvnw verify -P "${{ matrix.profile }}" -B
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Coverage
      run: ./mvnw -P coverage coveralls:report -B -D repoToken=${{ secrets.COVERALLS_TOKEN
        }}
    strategy:
      matrix:
        profile:
        - ''
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yaml
