jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      id: notes
      name: Extract Release Notes
      uses: ffurrer2/extract-release-notes@v1.16.0
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.notes.outputs.release_notes }}
        draft: false
        prerelease: ${{ contains(github.ref, 'RC') }}
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yaml
